### ISSUE TITLE
Dependency vulnerability

### ISSUE THREAD

**Issue by chandanch** [zkat/ssri#13]
Seems like adding in package.json and pushing to github shows the `Dependency vulnerability` warning

**Comment by alvarotrigo** [comment]
+1

**Comment by iarna** [comment]
As the advisory says, you need to update to ssri@5.2.2 or later. There's no action to be taken here.

**Comment by alvarotrigo** [comment]
Thanks!

**Comment by umimehar** [comment]
@iarna can you tell me how i can update to ssri@5.2.2 manually as its a dependency of one of my project dependency.

**Comment by alvarotrigo** [comment]
@umimehar sure! Not quite sure which dependency makes use of it, but I just did a `npm update` to update all my dependencies and that fixed it :)  

You can see my commit [here](https://github.com/alvarotrigo/vue-fullpage.js/commit/bdc22efd3ef536c214d0452fe14361d4f523a5ea#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

**Comment by zkat** [comment]
This was resolved pretty much around the same time the advisory went out, if not before. So I'm closing this. If you're getting a warning about this, just update your ssri version.

But again, it's almost certain you're not gonna be vulnerable to it for most situations where this package gets used in practice.
