### ISSUE TITLE
Issues with upgrading to NPM 5

### ISSUE THREAD

**Issue by bjornharvold** [zkat/ssri#3]
Node 7.10
NPM 5.0.1

13382 silly pacote trying rimraf@https://registry.npmjs.org/rimraf/-/rimraf-2.6.1.tgz by hash: sha1-wjOOxkPfeht/5cVPqG9XQopV8z0=
13383 verbose stack TypeError: Cannot read property 'find' of undefined
13383 verbose stack     at opts.integrity.digests.find.hash (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:264:33)
13383 verbose stack     at Array.find (native)
13383 verbose stack     at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:263:15)
13383 verbose stack     at emitNone (events.js:91:20)
13383 verbose stack     at Transform.emit (events.js:188:7)
13383 verbose stack     at endReadableNT (_stream_readable.js:975:12)
13383 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
13383 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by AdrienLemaire** [comment]
Same versions, same error

**Comment by AdrienLemaire** [comment]
I'm not clear about the code, but it looks like [this digests variable](https://github.com/zkat/ssri/blob/latest/index.js#L263) is a string (hexDigest ?) instead of a buffer, which is an object with the find() method available.

**Comment by AdrienLemaire** [comment]
Found the fix in this issue: https://github.com/npm/npm/issues/16677

Run `npm cache verify` to get rid of this error

**Comment by bjornharvold** [comment]
That did the trick. Thank you!

**Comment by abhinavsingi** [comment]
It didn't for me - maybe this can help - but this is also open
https://github.com/zkat/ssri/issues/7
