### ISSUE TITLE
Output corresponding package on integrity-checksum mismatch

### ISSUE THREAD

**Issue by danielreiser** [zkat/ssri#7]
I guess I am not the only one running into an integrity-checksum mismatch at one point during development (issues were created previously and are still open in the npm issues section). Unfortunately the error which is thrown doesn't include any information about the corresponding package(besides the expected checksum).

Sample output:
`sha1-/ts5T58OAasdasdasdasdasqqXaOcCvaI7UF+ufh8= integrity checksum failed when using sha1: wanted sha1-/ts5T58OAasdasdasdasdasqqXaOcCvaI7UF+ufh8= but got sha1-/ts5T58OAqqXaOcCvaI7UF+ufh8=. (2995 bytes)`

**My env:**
node 8.4.0
npm 5.3.0
os x 10.12.5

**How to replicate:**
In an ideal situation this error doesn't get thrown therefore manually editing a integrity hash inside package-lock.json does the trick.

This could also be handles by npm. As the error is constructed in this context I therefore wanted to create this issue here first. Shouldn't be too hard to handle if npm passes the package name to ssri.fromHex as an additional prop in the options object.

**Comment by pastinepolenta** [comment]
+1

**Comment by abhinavsingi** [comment]
@danielreiser @stilllife00 - Any way to check the package name from in ssri?
Couldn't find if in node the package name is getting passed.

**Comment by grawk** [comment]
+1

**Comment by aheckmann** [comment]
I've hacked my local version of npm to expose this info as a temp workaround.

Relates to https://github.com/npm/npm/issues/18957

**Comment by zkat** [comment]
ssri is not the right place for this. `pacote` [has already fixed this itself](https://github.com/zkat/pacote/blob/latest/lib/with-tarball-stream.js#L124-L130).

So, I'm closing this.
